fix(687): Add Slack notifications settings for user and cluster admin
screwdriver-cd/guide pull request #140
Opened 2018-01-22 19:52 UTC by tkyi

## Context
Have added new Slack functionality.

## Objective
This PR:
- updates documentation with new Slack notifications feature.
- adds Slack notifications repo to contributing doc
- switches order of description section on the guide landing page

![screencapture-127-0-0-1-4000-user-guide-configuration-settings-1516650369165](https://user-images.githubusercontent.com/3230529/35241174-7ab687c6-ff6a-11e7-964d-cc564ed342b3.png)

<img width="842" alt="screen shot 2018-01-22 at 11 33 38 am" src="https://user-images.githubusercontent.com/3230529/35241184-7fdb12f8-ff6a-11e7-99f9-feae161db80a.png">

## Related links
- Slack notifications repo: https://github.com/screwdriver-cd/notifications-slack
- Original issue: https://github.com/screwdriver-cd/screwdriver/issues/687

2018-01-22 20:17 UTC, d2lam commented on docs/user-guide/configuration/settings.md
> +This Slack setting will send Slack notifications to `mychannel` and `my-other-channel` on all build statuses:
The status thing is same behavior for email and slack, maybe we can say this part in the common section.

2018-01-22 22:01 UTC, minzcmu requested changes

2018-01-22 22:01 UTC, minz1027 commented on docs/cluster-management/configure-api.md
> +Create a `screwdriver-bot` user in your Slack instance. Generate a Slack token for the new user and set it in your Slack notifications settings.
`screwdriver-bot` is a bot user not a regular user. Can we say `screwdriver-bot` bot user and link it with https://api.slack.com/bot-users?

2018-01-23 19:40 UTC, jithine approved these changes

2018-01-23 20:08 UTC, d2lam approved these changes

2018-01-23 20:09 UTC, merged