Translate 'Submitting Pull Request' in contributing.md into Japanese
screwdriver-cd/guide pull request #144
Opened 2018-02-15 15:15 UTC by tomotargz

2018-02-15 16:11 UTC, catto requested changes
PRありがとうございます！ 表記ゆれについては修正をお願いします

2018-02-15 16:11 UTC, catto commented on docs/ja/about/contributing.md
> +- 良いコミットメッセージを現在形で(Added XではなくAdd Xのように)書いて下さい！タイトルは短くし、本文には必要なら空行や箇条書きを使って下さい。タイトルと箇条書きの先頭文字は大文字にしてください。タイトルに句読点は不要です。
`下さい`に表記ゆれがありますのでどちらかに統一をお願いします。個人的にはひらがなが好みです

2018-02-15 16:11 UTC, catto commented on docs/ja/about/contributing.md
> +- すべての公開関数は文書化される必要があります。READMEやこの[ガイド](https://github.com/screwdriver-cd/guide)に説明を追加してください。
文書化されている必要があります　のほうが自然に感じますがいかがでしょう

2018-02-15 16:11 UTC, catto commented on docs/ja/about/contributing.md
> +- テストカバレッジを上げデグレードを防ぐためにテストコードを書いて下さい。
日本語だとregressionはデグレードと言われることが多いかもしれませんが、シンプルに"バグの発生や再発"などにしても良さそうですね。好みの問題かもです。

意味的には"書いてください"でとても正しいのですが、Pull requestに含めてほしいという意図を込めて"テストコードを追加してください"と訳しても良いのかもしれません。

2018-02-16 04:38 UTC, tomotargz commented
@catto レビューありがとうございます！

* 表記ゆれを修正しました。(下さい→ください)
* 提案してくれた表現の方が私のものよりわかりやすく感じたので、ひととおり修正しました。

2018-02-16 13:08 UTC, okuryu commented on docs/ja/about/contributing.md
> +- コードはリンターとスタイルチェックにパスする必要があります。
「スタイルチェックに」→「スタイルチェックを」の方が自然な気がします。

2018-02-16 13:08 UTC, okuryu commented on docs/ja/about/contributing.md
> +- すべての公開関数は文書化されている必要があります。READMEやこの[ガイド](https://github.com/screwdriver-cd/guide)に説明を追加してください。
「external method」というのは関数というよりも「手順」や「方法」といった意味じゃないでしょうか。「すべての手順は文書化されている必要があります。」といった感じはどうでしょうか。

2018-02-16 13:08 UTC, okuryu commented on docs/ja/about/contributing.md
> +- テストカバレッジを上げバグの発生や再発を防ぐためにテストコードを含めてください。
「テストカバレッジ」は「コードカバレッジ」の方が一般的だと思います。

2018-02-16 15:07 UTC, tomotargz commented
@okuryu ありがとうございます！修正しました！

2018-02-17 02:29 UTC, okuryu approved these changes
👍

2018-02-19 09:49 UTC, catto approved these changes

2018-02-19 09:50 UTC, merged

2018-02-19 09:51 UTC, catto commented
@tomotargz ありがとうございました！ 👍