Translate `Commit Message Format` in contributing.md into Japanese
screwdriver-cd/guide pull request #146
Opened 2018-02-19 10:10 UTC by tomotargz

2018-02-21 18:56 UTC, tkyi commented
We can merge this once it looks good to someone else from Yahoo Japan 👍

2018-02-23 07:48 UTC, catto commented
@tkyi 🙆

2018-02-23 07:57 UTC, catto requested changes
PRありがとうございます 🙇 レビュー内容をご確認ください

2018-02-23 07:57 UTC, catto commented on docs/ja/about/contributing.md
> +私たちは[semantic-release](https://www.npmjs.com/package/semantic-release)を利用しているので、コミットメッセージは`<type>(<scope>): <subject>`のようなフォーマットでなければいけません。
このフォーマットである必要があるので、"ような"は削除したほうがよいです

2018-02-23 07:57 UTC, catto commented on docs/ja/about/contributing.md
> +- Subject: コミットの説明。メジャーバージョンと互換性がなくなる変更のときはコミットメッセージのどこかに`BREAKING CHANGE`と書いてください。
メジャーバージョンと互換性がなくなる変更の時ではなく、メジャーバージョンの更新が必要となる互換性のない変更が行われる際というような説明が正しそうです。

2018-02-23 07:57 UTC, catto commented on docs/ja/about/contributing.md
> +### コミットメッセージ
"のフォーマット" があってもよいですね

2018-02-26 11:57 UTC, tomotargz commented
@catto レビューありがとうございます 😃 
修正しました。

2018-02-27 02:57 UTC, catto approved these changes
👍

2018-02-27 04:38 UTC, merged