fix: add documentation for independent jobs
screwdriver-cd/guide pull request #152
Opened 2018-03-07 16:58 UTC by jithin1987

2018-03-07 17:50 UTC, tkyi commented on docs/user-guide/configuration/workflow.md
> +## Re-running a job's build
Not sure this belongs in the configuration section of the documentation.
Maybe move it to https://docs.screwdriver.cd/user-guide/FAQ or just have `### Re-running a job's build` as a section under `## Detached Jobs and Pipelines`

2018-03-07 19:06 UTC, minzcmu requested changes

2018-03-07 19:06 UTC, minz1027 commented on docs/user-guide/configuration/workflow.md
> +2. Click on the the job icon from the graph and click "Start pipeline from here"
Can we add a line here saying that you can see this only after you log in?

2018-03-08 07:57 UTC, tkyi approved these changes
LGTM 👍

2018-03-08 18:29 UTC, minzcmu approved these changes
👍 good to go

2018-03-08 18:29 UTC, merged