fix(1007): Add sonar coverage docs
screwdriver-cd/guide pull request #191
Opened 2018-05-11 01:09 UTC by tkyi

Adding Sonar coverage docs

_Note: not sure where to put the user config part._

Related to https://github.com/screwdriver-cd/screwdriver/issues/1007

2018-05-11 17:04 UTC, minzcmu requested changes

2018-05-11 17:04 UTC, minz1027 commented on docs/user-guide/configuration/coverage.md
> +Alternatively, you can add configurations to the environment variable `$SD_SONAR_OPTS`.
We shall mention that if they have defined same property in both way, $SD_SONAR_OPTS will override the properties file

2018-05-11 17:04 UTC, minz1027 commented on docs/user-guide/configuration/coverage.md
> +sonar.javascript.lcov.reportPath=artifacts/coverage/lcov.info
We should say something that the reportPath property is different depends on language. They should check this doc to figure out the right syntax: https://docs.sonarqube.org/display/PLUG

2018-05-11 17:08 UTC, minzcmu requested changes

2018-05-11 17:08 UTC, minz1027 commented on docs/user-guide/configuration/coverage.md
> +### Related links
Can add a reference for all sonar properties: https://docs.sonarqube.org/display/SONAR/Analysis+Parameters

2018-05-11 23:02 UTC, minzcmu approved these changes

2018-05-14 22:15 UTC, jithine approved these changes

2018-05-14 22:16 UTC, merged