Update links for Kubernetes yaml files
screwdriver-cd/guide pull request #36
Opened 2016-10-03 21:58 UTC by tkyi

- Short-term fix for broken links in Cluster Setup page
- Added some more newlines for formatting issues

Relates to https://github.com/screwdriver-cd/guide/issues/35

2016-10-03 22:00 UTC, d2lam requested changes

2016-10-03 22:00 UTC, d2lam commented on docs/getting-started/cluster-setup.md
> +You can check out the [Screwdriver Kubernetes repo](https://github.com/screwdriver-cd/kubernetes) and for service and deployment definitions for running the Screwdriver API. Both files are required t
`and look for`

2016-10-03 22:03 UTC, petey commented on docs/getting-started/cluster-setup.md
> +You can check out the [Screwdriver Kubernetes repo](https://github.com/screwdriver-cd/kubernetes) and for service and deployment definitions for running the Screwdriver API. Both files are required t
Which file(s) are service and which are deployment definitions? There are a lot of files in that repo.

2016-10-04 00:06 UTC, tkyi commented on docs/getting-started/cluster-setup.md
> +You can check out the [Screwdriver Kubernetes repo](https://github.com/screwdriver-cd/kubernetes) and for service and deployment definitions for running the Screwdriver API. Both files are required t
just dropped the `and`

2016-10-04 00:06 UTC, tkyi commented on docs/getting-started/cluster-setup.md
> +You can check out the [Screwdriver Kubernetes repo](https://github.com/screwdriver-cd/kubernetes) and for service and deployment definitions for running the Screwdriver API. Both files are required t
Addressed!

2016-10-04 00:09 UTC, petey commented on docs/getting-started/cluster-setup.md
> +You can check out the [Screwdriver Kubernetes repo](https://github.com/screwdriver-cd/kubernetes) and for service and deployment definitions for running the Screwdriver API. Both files are required t
My beef was with "Both files are required to deploy Screwdriver." This line makes me think there should be two files to look at, and not a multitude.

2016-10-04 01:00 UTC, tkyi commented on docs/getting-started/cluster-setup.md
> +You can check out the [Screwdriver Kubernetes repo](https://github.com/screwdriver-cd/kubernetes) and for service and deployment definitions for running the Screwdriver API. Both files are required t
Ahh I see
Fixed! I just deleted that extra line. Service and Deployment used to be defined in separate files; in the new Kubernetes repo they are both defined in one file (api.yaml)

2016-10-04 03:48 UTC, stjohnjohnson approved these changes
Reasonable changes

2016-10-04 05:02 UTC, petey approved these changes
I'm cool with this.

![blue_eyes_cat__belly_rub__no_emotion](https://cloud.githubusercontent.com/assets/78533/19063159/08ba3c98-89b5-11e6-9c1f-55de9c10d13d.gif)

2016-10-04 06:44 UTC, d2lam approved these changes
![](https://media2.giphy.com/media/Hc8PMCBjo9BXa/200w.gif)

2016-10-04 06:44 UTC, merged