Add documentation about build secrets
screwdriver-cd/guide pull request #37
Opened 2016-10-07 01:08 UTC by petey

2016-10-07 01:13 UTC, d2lam commented on docs/getting-started/secrets.md
> +Secrets may only be added, modified, or removed by people that are listed as admins of the git repository associated with a given pipeline.
Should we also mention that people with write can view secrets (just name, not value) that belong to a pipeline, or a build

2016-10-07 16:59 UTC, minzcmu requested changes

2016-10-07 16:59 UTC, minz1027 commented on docs/getting-started/secrets.md
> +POST /secrets/:id
Here should be `PUT`?

2016-10-07 16:59 UTC, minz1027 commented on docs/getting-started/secrets.md
> +## Screwdriver API
And we also have `GET /secrets/:id`

2016-10-07 17:23 UTC, petey commented on docs/getting-started/secrets.md
> +Secrets may only be added, modified, or removed by people that are listed as admins of the git repository associated with a given pipeline.
ok

2016-10-07 17:24 UTC, petey commented on docs/getting-started/secrets.md
> +## Screwdriver API
I'll expose the fetch-all from pipeline. The fetch-single endpoint is less useful to end users.

2016-10-07 17:24 UTC, petey commented on docs/getting-started/secrets.md
> +POST /secrets/:id
yes

2016-10-07 20:36 UTC, minzcmu approved these changes

2016-10-07 22:16 UTC, tkyi commented on docs/getting-started/secrets.md
> +For your own security, Screwdriver doesn't recommend exposing secrets to pull-request builds. Pull-request jobs can be created with modified `screwdriver.yaml` files including changes to the secrets
`For your own security, we don't`

2016-10-07 22:17 UTC, tkyi commented on docs/getting-started/secrets.md
> +Secrets may only be added, modified, or removed by people that are listed as admins of the git repository associated with a given pipeline. Admins may also fetch a list of secrets, but not the secret
capitalize `Git`

2016-10-07 23:56 UTC, stjohnjohnson approved these changes
Love it! Merge after the tweaks from @tkyi

2016-10-08 01:08 UTC, petey commented on docs/getting-started/secrets.md
> +For your own security, Screwdriver doesn't recommend exposing secrets to pull-request builds. Pull-request jobs can be created with modified `screwdriver.yaml` files including changes to the secrets
fixed.

2016-10-08 01:08 UTC, petey commented on docs/getting-started/secrets.md
> +Secrets may only be added, modified, or removed by people that are listed as admins of the git repository associated with a given pipeline. Admins may also fetch a list of secrets, but not the secret
fixed.

2016-10-08 01:08 UTC, merged