docs: Japanese translation 20200422
screwdriver-cd/guide pull request #379
Opened 2020-05-11 06:37 UTC by ibu1224

## Context
Update Japanese translation about this [comparison](https://github.com/screwdriver-cd/guide/compare/v0.0.256...v0.0.262?diff=unified)

## Objective
Update Japanese translation.

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-05-11 07:35 UTC, yoshwata commented
https://github.com/screwdriver-cd/guide/blob/master/docs/_data/menu_ja.yml
これの修正も必要ですか？

2020-05-11 07:38 UTC, yoshwata commented on docs/ja/cluster-management/configure-api.md
> +`queue` executorを使用すると、Resqueを含むRedisインスタを実行している[リモートキューサービス](./configure-queue-service)にビルドをキューすることができます。
インスタになってます

2020-05-11 07:41 UTC, yoshwata reviewed
https://github.com/screwdriver-cd/guide/pull/379/files#diff-7713d4c90a55930d02cc072b259bbe14R368
ここ消さなくていいでしょうか

2020-05-11 07:41 UTC, wahapo requested changes
[configuration/build-cache.md](https://github.com/screwdriver-cd/guide/compare/v0.0.256...v0.0.262?diff=unified#diff-696a3f94d6cc6f0b78f11b1f6e6481cf)が漏れています

2020-05-11 07:41 UTC, wahapo commented on docs/ja/cluster-management/configure-queue-service.md
> +# config/local.yaml
Please use ```` ```yaml ````

2020-05-11 07:41 UTC, wahapo commented on docs/ja/user-guide/FAQ.md
> +
https://github.com/screwdriver-cd/guide/compare/v0.0.256...v0.0.262?diff=unified#diff-9f5fa9d7b58aeb8abcb69a97ddbe5c99R107

2020-05-11 07:41 UTC, wahapo commented on docs/ja/user-guide/FAQ.md
https://github.com/screwdriver-cd/guide/compare/v0.0.256...v0.0.262?diff=unified#diff-9f5fa9d7b58aeb8abcb69a97ddbe5c99R138

2020-05-11 07:41 UTC, wahapo commented on docs/ja/user-guide/FAQ.md
> +詳しくは[こちら](https://docs.screwdriver.cd/user-guide/environment-variables#user-configurable)のドキュメントをご確認ください。
[./environment-variables#ユーザ設定](https://docs.screwdriver.cd/ja/user-guide/environment-variables#%E3%83%A6%E3%83%BC%E3%82%B6%E8%A8%AD%E5%AE%9A)

2020-05-11 07:48 UTC, yoshwata commented on docs/ja/cluster-management/configure-queue-service.md
> +| JWT_ENVIRONMENT | いいえ      | JWTを生成するための変数 例: `prod`, `beta` JWTに環境変数を含ませたくない場合は、この環境変数を設定しないでください。`''`|
do not set it toを訳し忘れてそう

2020-05-11 07:57 UTC, kumada626 commented on docs/ja/cluster-management/configure-queue-service.md
> +私たちの画像には、バージョン(例: `v1.2.3`)とフローティングタグ`latest`, `stable`タグがついています。
ここのイメージは画像じゃなくてDockerイメージ？

2020-05-11 07:57 UTC, kumada626 commented on docs/ja/cluster-management/configure-queue-service.md
> +最も良いインストール方法は、`stable`、または修正されたバージョンタグを使用することです。
他のコンポーネントの設定ページと記述を合わせると`特に理由がなければ`となりそう
https://docs.screwdriver.cd/ja/cluster-management/configure-store

2020-05-11 07:57 UTC, kumada626 commented on docs/ja/cluster-management/configure-queue-service.md
> +しかし、環境変数や `config/local.yaml`を上書きすることでデフォルトを上書きすることができます。
`config/local.yaml`は最初からあるものではなく上書きする場合に追加するものなので「config/local.yamlを上書き」はちょっと意味が違いそう

2020-05-11 07:57 UTC, kumada626 commented on docs/ja/cluster-management/configure-queue-service.md
> +APIから受診するJWTのバリデーションを設定します。
```suggestion
APIから受信するJWTのバリデーションを設定します。
```

2020-05-11 07:57 UTC, kumada626 commented on docs/ja/cluster-management/configure-queue-service.md
> +| JWT_ENVIRONMENT | いいえ      | JWTを生成するための変数 例: `prod`, `beta` JWTに環境変数を含ませたくない場合は、この環境変数を設定しないでください。`''`|
APIの方の記述と合わせたほうが良さそう
https://docs.screwdriver.cd/ja/cluster-management/configure-api

2020-05-11 07:57 UTC, kumada626 commented on docs/ja/cluster-management/configure-queue-service.md
> +ビルド成果物の保存に関するいくつかの設定を行います。
[misc] Redisキューの話なのにビルド成果物の話が出てきておかしい気がするけど英文の方から間違ってるのか……

2020-05-11 07:57 UTC, kumada626 commented on docs/ja/cluster-management/configure-queue-service.md
> +| REDIS_QUEUE_PREFIX  | いいえ                   | ''                   | Redis queue prefix          |
表の一連の説明が訳し忘れてる？

2020-05-11 07:58 UTC, yoshwata commented on docs/ja/cluster-management/configure-queue-service.md
> +| HTTPD_TLS | false               | SSL サポート、SSLの場合は`false`。[`tls.createServer`](https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener)で必要なオプションをJSONオブジェクトに置き換えます。|
TLS サポート、SSLの場合は〜が正しそう、英語がまちがってるのかな。

2020-05-11 08:00 UTC, yoshwata commented on docs/ja/cluster-management/configure-queue-service.md
> +# config/local.yaml
ここのyamlのが差分のものとちがう？

2020-05-11 08:05 UTC, yoshwata commented on docs/ja/cluster-management/developing-locally.md
> +## executor-queueまたはqueue serviceを使用してローカルで開発
andなので、executor-queueとqueue service かと思いました

2020-05-11 08:07 UTC, yoshwata commented on docs/ja/cluster-management/developing-locally.md
> +    plugin: queue # <- this step is essential in order to use queue
queue: '' がなさそう

2020-05-11 08:17 UTC, yoshwata commented on docs/ja/user-guide/FAQ.md
> +### 過去の成功時のビルドを再実行、Detached Jobを実行するには？
英語と比べると「成功時の」がいらないきがします

2020-05-11 08:19 UTC, yoshwata commented on docs/ja/user-guide/FAQ.md
> +3. 再ビルドを行いたいジョブをクリックして、ポップアップから「Start pipeline from here」のリンクをクリックして、最後に「YES」を押してジョブを実行させます。
[imo] 英語と同じように1. 1. 1.でナンバリングしたほうが楽にメンテできそうです

2020-05-11 08:22 UTC, yoshwata commented on docs/ja/user-guide/FAQ.md
>  通常のパイプラインから独立したジョブ（detachedジョブ）を作成してロールバックを行う手順は下記の通りとなります。通常のパイプラインの最後のジョブ（下記の例ではジョブD）で`meta set`コマンドでイメージ名やバージョン情報のメタを設定し、ロールバック用のジョブ（下記の例ではdetached）で`meta get` コマンドを使用して設定されたメタ情報を取得します。detachedジョブ
差分だとここの文章が変更されてて下の箇条書き部分が削除されていそう

2020-05-11 08:23 UTC, yoshwata commented on docs/ja/user-guide/FAQ.md
> +Detached Jobを実行するには？
これは不要でしょうか

2020-05-11 08:24 UTC, yoshwata commented on docs/ja/user-guide/FAQ.md
> +ビルド中に[API](./api)を呼び出すことで、ビルドのステータスを`UNSTABLE`にすることができます。Screwdriver.cdは、このステータスで表示されたビルドを失敗とみなし後続のジョブを実行しません。
not successfulなので失敗ではないかもと思いました。成功ではないものとみなし〜がよいでしょうか

2020-05-11 23:50 UTC, ibu1224 commented on docs/ja/cluster-management/configure-api.md
> +`queue` executorを使用すると、Resqueを含むRedisインスタを実行している[リモートキューサービス](./configure-queue-service)にビルドをキューすることができます。
タイポです修正します。

2020-05-11 23:50 UTC, ibu1224 commented on docs/ja/cluster-management/configure-queue-service.md
> +私たちの画像には、バージョン(例: `v1.2.3`)とフローティングタグ`latest`, `stable`タグがついています。
そうです、DockerImageでした

2020-05-11 23:50 UTC, ibu1224 commented on docs/ja/cluster-management/configure-queue-service.md
> +最も良いインストール方法は、`stable`、または修正されたバージョンタグを使用することです。
表現を合わせます

2020-05-11 23:50 UTC, ibu1224 commented on docs/ja/cluster-management/configure-queue-service.md
> +APIから受診するJWTのバリデーションを設定します。
修正します💦

2020-05-11 23:50 UTC, ibu1224 commented on docs/ja/cluster-management/configure-queue-service.md
> +| JWT_ENVIRONMENT | いいえ      | JWTを生成するための変数 例: `prod`, `beta` JWTに環境変数を含ませたくない場合は、この環境変数を設定しないでください。`''`|
訳し忘れてました

2020-05-11 23:50 UTC, ibu1224 commented on docs/ja/cluster-management/configure-queue-service.md
> +| JWT_ENVIRONMENT | いいえ      | JWTを生成するための変数 例: `prod`, `beta` JWTに環境変数を含ませたくない場合は、この環境変数を設定しないでください。`''`|
記述を統一します

2020-05-11 23:50 UTC, ibu1224 commented on docs/ja/cluster-management/configure-queue-service.md
> +| HTTPD_TLS | false               | SSL サポート、SSLの場合は`false`。[`tls.createServer`](https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener)で必要なオプションをJSONオブジェクトに置き換えます。|
修正しました、英語が違いそうでした

2020-05-11 23:50 UTC, ibu1224 commented on docs/ja/cluster-management/configure-queue-service.md
> +| REDIS_QUEUE_PREFIX  | いいえ                   | ''                   | Redis queue prefix          |
説明の部分が英語になってました
修正します。

2020-05-11 23:50 UTC, ibu1224 commented on docs/ja/cluster-management/configure-queue-service.md
> +ビルド成果物の保存に関するいくつかの設定を行います。
英文の修正を待つか、日本語版だけを先に修正するべきか迷います

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/cluster-management/configure-queue-service.md
> +# config/local.yaml
add to ```yaml

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/cluster-management/configure-queue-service.md
> +# config/local.yaml
コピー元間違えてました、修正します

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/cluster-management/developing-locally.md
> +## executor-queueまたはqueue serviceを使用してローカルで開発
翻訳ミスです修正します

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/user-guide/FAQ.md
> +### 過去の成功時のビルドを再実行、Detached Jobを実行するには？
以前のを流用してました、消します

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/user-guide/FAQ.md
> +
画像を入れるように修正しました

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/cluster-management/developing-locally.md
> +    plugin: queue # <- this step is essential in order to use queue
追加しました

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/user-guide/FAQ.md
> +3. 再ビルドを行いたいジョブをクリックして、ポップアップから「Start pipeline from here」のリンクをクリックして、最後に「YES」を押してジョブを実行させます。
ナンバリングに修正します

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/user-guide/FAQ.md
> +Detached Jobを実行するには？
以前のものを流用してました、消します

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/user-guide/FAQ.md
>  通常のパイプラインから独立したジョブ（detachedジョブ）を作成してロールバックを行う手順は下記の通りとなります。通常のパイプラインの最後のジョブ（下記の例ではジョブD）で`meta set`コマンドでイメージ名やバージョン情報のメタを設定し、ロールバック用のジョブ（下記の例ではdetached）で`meta get` コマンドを使用して設定されたメタ情報を取得します。detachedジョブ
消します

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/user-guide/FAQ.md
訳を修正します

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/user-guide/FAQ.md
> +ビルド中に[API](./api)を呼び出すことで、ビルドのステータスを`UNSTABLE`にすることができます。Screwdriver.cdは、このステータスで表示されたビルドを失敗とみなし後続のジョブを実行しません。
表現を修正します

2020-05-12 01:49 UTC, ibu1224 commented on docs/ja/user-guide/FAQ.md
> +詳しくは[こちら](https://docs.screwdriver.cd/user-guide/environment-variables#user-configurable)のドキュメントをご確認ください。
日本語のリンクへ修正します

2020-05-12 03:07 UTC, wahapo commented on docs/ja/user-guide/FAQ.md
>  1. ログインする。
このステップは削除されています
https://github.com/screwdriver-cd/guide/compare/v0.0.256...v0.0.262?diff=unified#diff-9f5fa9d7b58aeb8abcb69a97ddbe5c99L111

2020-05-12 03:07 UTC, wahapo commented on docs/ja/user-guide/FAQ.md
> +1. 再ビルドを行いたいジョブをクリックして、ポップアップから「Start pipeline from here」のリンクをクリックして、最後に「YES」を押してジョブを実行させます。
英語版と同じステップ数に分割したほうがよいかと思います
https://github.com/screwdriver-cd/guide/compare/v0.0.256...v0.0.262?diff=unified#diff-9f5fa9d7b58aeb8abcb69a97ddbe5c99R132-R134

2020-05-12 03:07 UTC, wahapo commented on docs/ja/user-guide/configuration/build-cache.md
> +## キャッシュの削除
なぜ「特定のジョブでキャッシュを無効にする」の上に持ってきました？
v0.0.262では「特定のジョブでキャッシュを無効にする」の英語ドキュメントは存在しないです。
https://github.com/screwdriver-cd/guide/compare/v0.0.256...v0.0.262?diff=unified#diff-696a3f94d6cc6f0b78f11b1f6e6481cfR67-R70

もしかしてv0.0.262の翻訳ではこのファイルはダウングレードになってしまいますか？

2020-05-12 03:34 UTC, ibu1224 commented on docs/ja/user-guide/configuration/build-cache.md
> +## キャッシュの削除
移動させたのは順番が変わったのかなとか思い移動しましたが、「特定のジョブでキャッシュを無効にする」がな買ったことに気づかなかったので場所を元に戻しておきます。

> もしかしてv0.0.262の翻訳ではこのファイルはダウングレードになってしまいますか

ダウングレードになってます、最新版では復活しているようです。
https://github.com/screwdriver-cd/guide/compare/v0.0.256...v0.0.268?diff=unified#diff-696a3f94d6cc6f0b78f11b1f6e6481cfR69

2020-05-12 03:37 UTC, ibu1224 commented on docs/ja/user-guide/FAQ.md
>  1. ログインする。
削除します

2020-05-12 03:39 UTC, ibu1224 commented on docs/ja/user-guide/FAQ.md
> +1. 再ビルドを行いたいジョブをクリックして、ポップアップから「Start pipeline from here」のリンクをクリックして、最後に「YES」を押してジョブを実行させます。
ステップ数を合わせます

2020-05-12 04:26 UTC, yoshwata commented on docs/ja/cluster-management/developing-locally.md
>  ### queue-worker/config/default.yaml
worker -> service でしょうか

2020-05-12 05:21 UTC, wahapo commented on docs/ja/user-guide/FAQ.md
> +1.「YES」を押してジョブを実行させます。
`1.`の後に半角スペースが必要

2020-05-12 05:24 UTC, wahapo commented on docs/ja/user-guide/FAQ.md
> +1. 再ビルドを行いたいジョブをクリックして、ポップアップから「Start pipeline from here」のリンクをクリックします。
句読点の前後で別のステップになっているかと思います
https://github.com/screwdriver-cd/guide/compare/v0.0.256...v0.0.262?diff=unified#diff-9f5fa9d7b58aeb8abcb69a97ddbe5c99R132-R133

2020-05-12 05:26 UTC, wahapo commented on docs/ja/cluster-management/configure-queue-service.md
> +ビルド成果物の保存に関するいくつかの設定を行います。
英日同時に、あとで修正しましょう

2020-05-12 06:15 UTC, yoshwata approved these changes

2020-05-12 06:53 UTC, kumada626 commented on docs/ja/cluster-management/configure-queue-service.md
> +title: Configuring the Queue Service
タイトルが訳されてない

2020-05-12 06:53 UTC, kumada626 commented on docs/ja/cluster-management/configure-queue-service.md
> +menu: menu
ここのmenuもja用にする必要があります
```suggestion
menu: menu_ja
```

2020-05-12 06:53 UTC, kumada626 commented on docs/ja/cluster-management/configure-queue-service.md
> +| SECRET_JWT_SD_API_PUBLIC_KEY | *none*  | JWTの署名の検証に使用する公開鍵。APIで設定したものと同じものを使用してください。 |
細かいですが上がです。で終わってるのにここだけ公開鍵。と体言止めになってます。

2020-05-12 08:04 UTC, wahapo approved these changes
👍

2020-05-12 08:05 UTC, kumada626 approved these changes
LGTM

2020-05-12 08:05 UTC, merged