Add event to domain model
screwdriver-cd/guide pull request #43
Opened 2016-11-03 21:26 UTC by d2lam

Relates to https://github.com/screwdriver-cd/screwdriver/issues/221

2016-11-03 22:34 UTC, tkyi approved these changes

2016-11-03 22:47 UTC, minzcmu requested changes

2016-11-03 22:47 UTC, minz1027 commented on docs/internals/domain.md
>   - `aborted` - User canceled the running build
Make them uppercase?
https://api.screwdriver.cd/v4/jobs/d7ffb6551e07f6f0cd06e4bd290ea71bffb2bf3b/builds

2016-11-03 22:47 UTC, minz1027 commented on docs/internals/domain.md
> +- `pr`:  - Events created by opening, closing, or synchronizing a pull request. This type of event only triggers the `main` job.
No closing

2016-11-04 00:26 UTC, minzcmu approved these changes

2016-11-04 00:27 UTC, merged