docs: japanese translation202301
screwdriver-cd/guide pull request #565
Opened 2023-01-13 07:21 UTC by itleigns

## Context
Update Japanese documents about [this comparison](https://github.com/screwdriver-cd/guide/compare/7ecad54de55332a60b4ddb1f5bf276a29c460d6b...b34ff87d80f2743b678bc77251fef6d4c098d3a8).

## Objective

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2023-01-13 08:23 UTC, yk634 requested changes

2023-01-13 08:23 UTC, yk634 commented on docs/ja/user-guide/configuration/externalConfig.md
>  ![External config child pipeline ](../../../user-guide/assets/external-config-child.png)
画像が違いますかね？
```suggestion
![External config child pipeline ](../../../user-guide/assets/external-config-child-active.png)
```

2023-01-13 08:43 UTC, yk634 approved these changes, later dismissed

2023-01-16 00:01 UTC, kumada626 commented on docs/ja/about/contributing/index.md
> +**重要:** メジャーバージョンを更新する必要のある**破壊的変更**の際には、コミットメッセージに `BREAKING CHANGE: <message>` を追加し、その前にスペースか改行を2文字入れてください。そしてコミットメッセージの残りの部分はその説明に使ってください。
コミットメッセージの「フッターに」とした方がより正確かな。元の文にも入ってるしライブラリの仕様でも言及されている箇所なので
https://github.com/semantic-release/semantic-release#commit-message-format

2023-01-16 00:55 UTC, itleigns commented on docs/ja/about/contributing/index.md
> +**重要:** メジャーバージョンを更新する必要のある**破壊的変更**の際には、コミットメッセージに `BREAKING CHANGE: <message>` を追加し、その前にスペースか改行を2文字入れてください。そしてコミットメッセージの残りの部分はその説明に使ってください。
修正しました。

2023-01-16 02:09 UTC, kumada626 approved these changes

2023-01-17 01:35 UTC, yk634 approved these changes

2023-01-17 01:36 UTC, merged