refactor: simple dev makefile
screwdriver-cd/guide pull request #59
Opened 2016-12-03 00:32 UTC by FenrirUnbound

I don't like globally adding packages and binaries in my dev environment. This is the `Makefile` I've been using for developing with the guide. It still assumes that you have python and pip available on your system.

It creates a virtualenv and saves all the dependencies to it. The default target will create the virutalenv if it doesn't exist and then activate it prior to serving the docs locally.

Virtualenv reference: https://virtualenv.pypa.io/en/stable/

2016-12-06 19:30 UTC, petey requested changes
Can you update the readme to talk about the new flow for installation and development?

2016-12-06 23:20 UTC, FenrirUnbound commented
I wasn't sure if other folks want to adopt the new way, so I kept both methods in the README. If your suggestion was to adopt this way entirely, then I could replace the old method.

2016-12-06 23:57 UTC, petey approved these changes

2016-12-07 00:01 UTC, tkyi approved these changes
![](http://media1.giphy.com/media/3oriOb4jTB1nAnI8gM/200w.gif)

2016-12-07 00:01 UTC, merged