feat: configuring UI & Store components
screwdriver-cd/guide pull request #63
Opened 2016-12-10 01:04 UTC by FenrirUnbound

Documented some of my knowledge regarding SD-in-a-box and how to plug in your development instance.

The API is a beast to do, so I'll brain-dump that after I'm done with our yearly accounting 😸

2016-12-10 01:06 UTC, tkyi commented
build failed

```bash
$ markdownlint docs/
Using config from .markdownlint
docs/cluster-management/running-locally.md:27: R2 Line has trailing whitespace
docs/cluster-management/running-locally.md:63: R2 Line has trailing whitespace
docs/cluster-management/running-locally.md:115: R2 Line has trailing whitespace
```

2016-12-10 01:16 UTC, FenrirUnbound commented
@tkyi Thanks for letting me know. 

Fixed 😺

2016-12-10 09:06 UTC, d2lam requested changes

2016-12-10 09:06 UTC, d2lam commented on docs/cluster-management/running-locally.md
> +Since it's powered by Docker, you can determine which images to use for it
Maybe add a link to the list of available images: https://hub.docker.com/r/screwdrivercd/

2016-12-10 09:10 UTC, d2lam requested changes

2016-12-10 09:10 UTC, d2lam commented on docs/cluster-management/running-locally.md
> +We could do a blog post on locally building a docker image that extends one of the Screwdriver ones.
We should add what command to run after they modify the images (for people who are not familiar with docker-compose):
```
docker-compose -p screwdriver up
```

2016-12-11 21:11 UTC, FenrirUnbound commented on docs/cluster-management/running-locally.md
> +Since it's powered by Docker, you can determine which images to use for it
Good idea.

We can add a list of the specific docker images with some short explanation. Like

* screwdrivercd/screwdriver - Screwdriver API. The main engine of the CI/CD cluster.
* screwdrivercd/ui - Screwdriver UI. To pleasantly interact with Screwdriver
* screwdrivercd/store - Screwdriver artifact repository. Responsible for artifacts like logs & templates

2016-12-11 21:12 UTC, FenrirUnbound commented on docs/cluster-management/running-locally.md
> +We could do a blog post on locally building a docker image that extends one of the Screwdriver ones.
The SD-in-a-box tells you how to bring it up. Still, it wouldn't hurt to repeat the information here.

I still feel like this section is lacking. Any suggestions for making this part more meaningful?

2016-12-13 18:58 UTC, FenrirUnbound commented on docs/cluster-management/running-locally.md
> +We could do a blog post on locally building a docker image that extends one of the Screwdriver ones.
BTW, the command you suggested was plugged in the most recent commit (`9b2a300`, as of writing)

2016-12-13 19:56 UTC, tkyi commented on docs/cluster-management/running-locally.md
> +* [screwdrivercd/store](https://hub.docker.com/r/screwdrivercd/store) - Artifact repository. Responsible for artifacts like build logs & templates
Does SD-in-a-box use https://hub.docker.com/r/screwdrivercd/launcher?

2016-12-13 20:00 UTC, FenrirUnbound commented on docs/cluster-management/running-locally.md
> +* [screwdrivercd/store](https://hub.docker.com/r/screwdrivercd/store) - Artifact repository. Responsible for artifacts like build logs & templates
In general, can you customize the launcher image?

2016-12-13 20:00 UTC, tkyi commented on docs/cluster-management/running-locally.md
> +      URI: http://11.22.33.44:8080             # Can't remember. Some way to tell the server what it's origin name is?
@stjohnjohnson

2016-12-13 20:00 UTC, tkyi commented on docs/cluster-management/running-locally.md
> +
Link to directions on how to configure the API here?

2016-12-13 20:01 UTC, tkyi commented on docs/cluster-management/running-locally.md
> +* [screwdrivercd/store](https://hub.docker.com/r/screwdrivercd/store) - Artifact repository. Responsible for artifacts like build logs & templates
Not really, but can you choose which version to use?

2016-12-13 20:14 UTC, FenrirUnbound commented on docs/cluster-management/running-locally.md
> +      URI: http://11.22.33.44:8080             # Can't remember. Some way to tell the server what it's origin name is?
Missed that. It's the value that the Launcher receives so it knows where to update the build progress, logs, and stuff.

2016-12-13 20:18 UTC, FenrirUnbound commented on docs/cluster-management/running-locally.md
> +* [screwdrivercd/store](https://hub.docker.com/r/screwdrivercd/store) - Artifact repository. Responsible for artifacts like build logs & templates
Doneskies

2016-12-13 20:18 UTC, FenrirUnbound commented on docs/cluster-management/running-locally.md
> +
Directions included

2016-12-13 22:22 UTC, tkyi approved these changes
👍 LGTM
![](http://media1.giphy.com/media/5wEZIZvDJS2is/200w.gif)

2016-12-14 07:39 UTC, d2lam approved these changes
I'm fine with this 👍  We can always go back and remove unnecessary docs as we improve our sd-in-a-box script.

2016-12-14 07:43 UTC, stjohnjohnson approved these changes
Looks good, hopefully we can remove a good chunk of this in the future.

2016-12-14 08:08 UTC, merged