Update links to Kuberenetes api.yaml file to point to different repo
screwdriver-cd/guide pull request #68
Opened 2017-01-17 18:39 UTC by tkyi

Moved Kubernetes example configs over to the `example-configs` repo, updating links in the guide to match

2017-01-17 18:39 UTC, yahoocla commented
CLA is valid!

2017-01-17 18:39 UTC, yahoocla commented
CLA is valid!

2017-01-17 18:39 UTC, yahoocla commented
CLA is valid!

2017-01-17 18:39 UTC, yahoocla commented
CLA is valid!

2017-01-17 18:58 UTC, d2lam commented on docs/cluster-management/kubernetes.md
> +You can check out the `api.yaml` in the [Screwdriver config examples repo](https://github.com/screwdriver-cd/config-examples) for service and deployment definitions to run the Screwdriver API.
This doesn't exist yet?

2017-01-17 22:34 UTC, tkyi commented on docs/cluster-management/kubernetes.md
> +You can check out the `api.yaml` in the [Screwdriver config examples repo](https://github.com/screwdriver-cd/config-examples) for service and deployment definitions to run the Screwdriver API.
oops should be `screwdriver-cd-test`

2017-01-18 00:14 UTC, d2lam requested changes

2017-01-18 00:14 UTC, d2lam commented on docs/cluster-management/kubernetes.md
> +It should look like the Service in [api.yaml](https://github.com/screwdriver-cd-test/config-examples/blob/master/kubernetes/api.yaml).
This link still doesn't work

2017-01-18 18:18 UTC, minzcmu requested changes
accident..

2017-01-18 18:19 UTC, minzcmu approved these changes

2017-01-18 18:42 UTC, d2lam commented
Waiting on https://github.com/screwdriver-cd-test/config-examples/pull/3/files

2017-01-19 01:13 UTC, d2lam approved these changes

2017-01-19 01:13 UTC, merged