feat: extending a docker image
screwdriver-cd/guide pull request #72
Opened 2017-01-27 22:14 UTC by FenrirUnbound

# Additional topics

Added documentation on how you can modify the bookend plugins to change the order of the built-in plugins. It also refers to custom plugins that are written in a different section.

Added documentation on how to use the API Docker image as a base and build on top of it, such as including custom dependencies.

## How a user could modify which built-in bookend plugins to use

![screen shot 2017-01-27 at 2 09 55 pm](https://cloud.githubusercontent.com/assets/721148/22389462/79eb7efa-e49a-11e6-85e2-e649a750bc7e.png)

## How a user would build on top of the API Docker image to embed their own bookend plugin

![screen shot 2017-01-27 at 2 04 23 pm](https://cloud.githubusercontent.com/assets/721148/22389468/80a92a9e-e49a-11e6-906f-1d556fa020a4.png)

# Styling Changes

Changed the header from a H2 to H1. This has a side-effect of cleaning up the sidebar to only show the high-level topics.

## Changed the heading 

![screen shot 2017-01-27 at 2 06 37 pm](https://cloud.githubusercontent.com/assets/721148/22389481/97a3f382-e49a-11e6-85d3-ee3f75203b31.png)

2017-01-30 20:29 UTC, stjohnjohnson requested changes
Looks good otherwise!  Just a quick rename of those fields.

2017-01-30 20:29 UTC, stjohnjohnson commented on docs/cluster-management/configure-api.md
> +ecosystem:
I'm changing this to `bookends` here https://github.com/screwdriver-cd/screwdriver/pull/444

2017-01-30 20:29 UTC, stjohnjohnson commented on docs/cluster-management/configure-api.md
> +You can globally configure which built-in bookend plugins will be used during a build. By default, `sd-scm` is enabled to begin builds with a SCM checkout command.
Switching to `scm` instead of `sd-scm`

2017-01-30 23:42 UTC, stjohnjohnson approved these changes
I approve of my own changes as well :)

2017-01-31 00:30 UTC, tkyi requested changes

2017-01-31 00:30 UTC, tkyi commented on docs/cluster-management/configure-api.md
> +If you're looking to include a custom bookend in the API, please refer to the *Using a custom bookend* topic in the *Extending the Docker container* section.
Could link the section by doing 
```md
[Extending the Docker container](http://docs.screwdriver.cd/cluster-management/configure-api/#extending-the-docker-container)
```

2017-01-31 00:30 UTC, tkyi commented on docs/cluster-management/configure-api.md
> +There are some scenarios where you would prefer to extend the ScrewdriverCD Docker image, such as using custom Bookend plugins. This section is not meant to be exhaustive or complete, but will provid
`Screwdriver Docker image`*?

2017-01-31 01:38 UTC, tkyi commented on docs/cluster-management/configure-api.md
> +### Using a custom bookend
Should the words be capitalized? It's okay. It looks okay.

2017-01-31 01:39 UTC, tkyi approved these changes
👍 Do the thing
![](http://media0.giphy.com/media/T8c3M3yWJcsKY/200w.gif)

2017-01-31 06:05 UTC, d2lam approved these changes
Looks good

2017-01-31 06:05 UTC, merged