fix: update metadata usage doc
screwdriver-cd/guide pull request #79
Opened 2017-03-15 23:22 UTC by minz1027

Update metadata usage doc

2017-03-15 23:29 UTC, tkyi requested changes

2017-03-15 23:29 UTC, tkyi commented on docs/about/appendix/domain.md
> +Metadata is a structured key/value storage of relevant information about a [build]. Metadata will be shared with subsequent [builds] in the same [workflow]. It can be updated or retrieved throughout
I think using `[build]` once is enough. The other mentions of "build" don't need to be linked.

2017-03-15 23:57 UTC, d2lam approved these changes

2017-03-16 00:15 UTC, minz1027 commented on docs/about/appendix/domain.md
> +Metadata is a structured key/value storage of relevant information about a [build]. Metadata will be shared with subsequent [builds] in the same [workflow]. It can be updated or retrieved throughout
addressed

2017-03-16 00:54 UTC, tkyi approved these changes
LGTM!
![](http://media0.giphy.com/media/yAOjunY81Trjy/200w.gif)

2017-03-16 00:54 UTC, merged